((prefs (xmult . 1000.0)
         (ymult . 1000.0)
         (max_tap_duration . 100)
         (show_press_duration . #f)
         (scroll_threshold . 10)
         (html_port . 8001)
         (websocket_port . 9001)
        )
  (gui (title . "Audacity")
        (control Sizer (orientation . Vertical)
                  (controls (Sizer (orientation . Horizontal)
                                    (controls (Label (label . "Mouse")
                                                      (proportion)
                                                     )
                                              )
                                    (proportion . (0.05))
                                   )
                             (Sizer (orientation . Horizontal)
                                     (controls (MouseButton (label . ("L"))
                                                             (button . LeftButton)
                                                             (proportion)
                                                            )
                                                (ScrollButton (label . ("Scroll"))
                                                               (proportion)
                                                              )
                                                (MouseButton (label . ("R"))
                                                              (button . RightButton)
                                                              (proportion)
                                                             )
                                               )
                                     (proportion . (0.05))
                                    )
                             (MouseXy (label)
                                       (proportion)
                                      )
                            )
                  (proportion)
                 )
       )
  (colors)
 )

